### PR TITLE
Simplify URL joiner (and fix #71)

### LINKED ISSUE #71: url join failed when path is relative and with out `./` and the host has query parameters
In this particular case, host url is `http://eqe003odff.eq.webcdn.stream.ne.jp/www50/eqe003odff/jmc_pub/jmc_pd/00015/92e7d2e1b50646f7b1576b65a8a17bee_crypt/92e7d2e1b50646f7b1576b65a8a17bee_23_cryptmedia.m3u8?__token=WrHTkk+ztKRIAZO80oWOwTGvOqO/uq8xzu+Gt0EcF9iP655SdUnE8zxDkIS476kg0yd8Nf+vlvOv2VLHwbt7JQ0Qi5wLtFfB55dL6c09Esk=jpZT6cVSfO8iTd9o` and the part path is `92e7d2e1b50646f7b1576b65a8a17bee_23_crypt_00001.ts`.

The join failed because  https://github.com/Last-Order/Minyami/blob/d6c9e3bce24b6996e56eb59d2d7a29653a9c500e/src/utils/common.ts#L11-L13 only deals with query parameters when the path starts with `./`.

### PR DESCRIPTION
**Pull request by fireattack**
No need to reinvent the wheel

### CODE REVIEW

**Comment by Last-Order** [comment]
Thank you.

**Comment by Last-Order** [comment]
landed in 4.2.2

**Comment by climba03003** [comment]
It break when I use the full path without host.

**Comment by fireattack** [comment]
Any example?

**Comment by climba03003** [comment]
I use it to download a custom file. `./1.m3u8`
Which cannot be parsed by `new URL`

**Comment by climba03003** [comment]
`host` passed in is not always a valid URL.

For example inside the common parser.
https://github.com/Last-Order/Minyami/blob/master/src/core/parsers/common.ts#L12

`m3u8Url` can be a file path (both absolute or relative) which cannot be parsed by `new URL`.

**Comment by fireattack** [comment]
Adding back 
```js
        if (path.startsWith("http")) {
            return path;
```
will restore the old behavior.

(If you look at it, it only really works with local m3u8 file + remote absolute URLs as resources; any other combination would break either way. But I guess that's enough. No one is using Minyami to process local `.ts` I guess.)

**Comment by climba03003** [comment]
> 
> 
> Adding back
> 
> ```js
>         if (path.startsWith("http")) {
>             return path;
> ```
> 
> will restore the old behavior.
> 
> (If you look at it, it only really works with local m3u8 file + remote absolute URLs as resources; any other combination would break either way. But I guess that's enough. No one is using Minyami to process local `.ts` I guess.)

Not sure for the local `.ts` part, but the `.key` can be local file.

**Pull request merged**
